# After the ASCII Header Below have a empty line this is the Culprit <3
add_newline = false

"$schema" = "https://starship.rs/config-schema.json"

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

# Folder
[directory]
style = "blue"
format = "[󰉋 $path]($style) "

# Git branch
[git_branch]
symbol = " "
style = "bright-black"
format = "[$symbol$branch]($style) "

# Git status (tiny but expressive)
[git_status]
style = "cyan"
format = "([$all_status$ahead_behind]($style)) "

conflicted = "⚔ "
untracked  = " "
modified   = " "
staged     = " "
renamed    = " "
deleted    = " "
stashed    = " "

# Command duration (only shows if command was slow)
[cmd_duration]
min_time = 500
style = "yellow"
format = "[󱦟 $duration]($style) "

# Prompt arrow
[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"
